### ISSUE TITLE
test email responses

### ISSUE THREAD

**Issue by chrisohaver** [chrisohaver/coredns#7]

**Comment by chrisohaver** [comment]
@yuewko, @chrisohaver, Try responding to this comment via email.

**Comment by yuewko** [comment]
Not hopeful…

--
Yue Ko
Staff Software Engineer, Cloud and Network Automation
Infoblox  |  Control Your Network
(T) +1-443-603-0249  (M) +1-410-991-6293
yko@infoblox.com<mailto:yko@infoblox.com>  |  www.infoblox.com<http://www.infoblox.com/>

**Comment by chrisohaver** [comment]
there is always hope

On Feb 5, 2018, at 11:35 AM, Yue Ko <notifications@github.com<mailto:notifications@github.com>> wrote:

Not hopeful…

--
Yue Ko
Staff Software Engineer, Cloud and Network Automation
Infoblox | Control Your Network
(T) +1-443-603-0249 (M) +1-410-991-6293
yko@infoblox.com<mailto:yko@infoblox.com><mailto:yko@infoblox.com> | www.infoblox.com<http://www.infoblox.com><http://www.infoblox.com/>

**Comment by chrisohaver** [comment]
I not robot.


On Feb 5, 2018, at 11:36 AM, CoreDNS Cibot <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello I am a robot.
